# Generated by Django 4.1.3 on 2022-11-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('msg', models.TextField(db_column='msg')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('reg_user', models.CharField(db_column='reg_user', max_length=20)),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='id', max_length=20, unique=True)),
                ('password', models.TextField(db_column='password')),
                ('name', models.CharField(db_column='name', max_length=5)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('status', models.CharField(db_column='status', default='2', max_length=1)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='api',
            fields=[
                ('api_no', models.AutoField(db_column='api_no', primary_key=True, serialize=False)),
                ('api_name', models.CharField(db_column='api_name', max_length=20)),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
                ('client_secret', models.CharField(db_column='client_secret', max_length=10)),
                ('service_account', models.CharField(db_column='service_account', max_length=50)),
                ('private_key', models.TextField(db_column='private_key')),
                ('scope', models.TextField(db_column='scope')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='NWAD.member')),
            ],
            options={
                'db_table': 'api',
                'managed': True,
            },
        ),
    ]
