# Generated by Django 4.1.3 on 2022-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('msg', models.TextField(db_column='msg')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('reg_user', models.CharField(db_column='reg_user', max_length=20)),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='id', max_length=20, unique=True)),
                ('password', models.TextField(db_column='password')),
                ('name', models.CharField(db_column='name', max_length=5)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('status', models.CharField(db_column='status', default='2', max_length=1)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
    ]
