# Generated by Django 4.1.3 on 2023-04-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='member_no',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='member_no',
        ),
        migrations.DeleteModel(
            name='log',
        ),
        migrations.RemoveField(
            model_name='scen',
            name='api_no',
        ),
        migrations.RemoveField(
            model_name='scen',
            name='bot_no',
        ),
        migrations.RemoveField(
            model_name='scen',
            name='member_no',
        ),
        migrations.RemoveField(
            model_name='scen',
            name='scen_type',
        ),
        migrations.RemoveField(
            model_name='scen_conn',
            name='scen_no',
        ),
        migrations.RemoveField(
            model_name='token',
            name='api_no',
        ),
        migrations.DeleteModel(
            name='api',
        ),
        migrations.DeleteModel(
            name='bot',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='scen',
        ),
        migrations.DeleteModel(
            name='scen_conn',
        ),
        migrations.DeleteModel(
            name='scen_type',
        ),
        migrations.DeleteModel(
            name='token',
        ),
    ]
