# Generated by Django 4.1.3 on 2022-11-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('api_no', models.AutoField(db_column='api_no', primary_key=True, serialize=False)),
                ('api_name', models.CharField(db_column='api_name', max_length=20)),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
                ('client_secret', models.CharField(db_column='client_secret', max_length=10)),
                ('service_account', models.CharField(db_column='service_account', max_length=50)),
                ('private_key', models.TextField(db_column='private_key')),
                ('scope', models.TextField(db_column='scope')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='NWAD.member')),
            ],
            options={
                'db_table': 'api',
                'managed': True,
            },
        ),
    ]
