# Generated by Django 4.1.3 on 2022-11-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_api', to='NWAD.member'),
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('token_no', models.AutoField(db_column='token_no', primary_key=True, serialize=False)),
                ('token', models.TextField(db_column='token')),
                ('type', models.CharField(db_column='type', max_length=10)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_token', to='NWAD.api')),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_token', to='NWAD.member')),
            ],
            options={
                'db_table': 'token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='bot',
            fields=[
                ('bot_no', models.AutoField(db_column='bot_no', primary_key=True, serialize=False)),
                ('bot_id', models.CharField(db_column='bot_id', max_length=10)),
                ('bot_secret', models.CharField(db_column='bot_secret', max_length=30)),
                ('bot_name', models.CharField(db_column='bot_name', max_length=10)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_bot', to='NWAD.member')),
            ],
            options={
                'db_table': 'bot',
                'managed': True,
            },
        ),
    ]
