# Generated by Django 4.1.3 on 2022-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0002_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='private_key',
            field=models.TextField(db_column='private_key', null=True),
        ),
    ]
