# Generated by Django 4.1.3 on 2023-04-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NWAD', '0002_remove_api_member_no_remove_bot_member_no_delete_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('api_no', models.AutoField(db_column='api_no', primary_key=True, serialize=False)),
                ('api_name', models.CharField(db_column='api_name', max_length=20)),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
                ('client_secret', models.CharField(db_column='client_secret', max_length=24)),
                ('service_account', models.TextField(db_column='service_account')),
                ('private_key', models.TextField(db_column='private_key')),
                ('scope', models.TextField(db_column='scope')),
                ('status', models.CharField(db_column='status', default='1', max_length=1)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='bot',
            fields=[
                ('bot_no', models.AutoField(db_column='bot_no', primary_key=True, serialize=False)),
                ('bot_id', models.CharField(db_column='bot_id', max_length=10)),
                ('bot_secret', models.TextField(db_column='bot_secret')),
                ('bot_name', models.CharField(db_column='bot_name', max_length=50)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'bot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('msg', models.TextField(db_column='msg')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('reg_user', models.CharField(db_column='reg_user', max_length=20)),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='id', max_length=20, unique=True)),
                ('password', models.TextField(db_column='password')),
                ('name', models.CharField(db_column='name', max_length=5)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('status', models.CharField(db_column='status', default='1', max_length=1)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('corp_name', models.TextField(db_column='corp_name', max_length=50)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scen',
            fields=[
                ('scen_no', models.AutoField(db_column='scen_no', primary_key=True, serialize=False)),
                ('scen_name', models.CharField(db_column='scen_name', max_length=20)),
                ('domain', models.CharField(db_column='domain', max_length=10)),
                ('channel', models.CharField(db_column='channel', max_length=40)),
                ('members', models.TextField(db_column='members')),
                ('status', models.CharField(db_column='status', default='1', max_length=1)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_scen', to='NWAD.api')),
                ('bot_no', models.ForeignKey(db_column='bot_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_bot_scen', to='NWAD.bot')),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_scen', to='NWAD.member')),
            ],
            options={
                'db_table': 'scen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scen_type',
            fields=[
                ('scen_type', models.AutoField(db_column='scen_type', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=20)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'scen_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('token_no', models.AutoField(db_column='token_no', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=20)),
                ('token', models.TextField(db_column='token')),
                ('scope', models.TextField(db_column='scope')),
                ('exp_date', models.DateTimeField(db_column='exp_date')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_token', to='NWAD.api')),
            ],
            options={
                'db_table': 'token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scen_conn',
            fields=[
                ('conn_no', models.AutoField(db_column='conn_no', primary_key=True, serialize=False)),
                ('reporter', models.CharField(db_column='reporter', max_length=40, null=True)),
                ('approver', models.CharField(db_column='approver', max_length=40, null=True)),
                ('status', models.CharField(db_column='status', default='2', max_length=1)),
                ('message', models.TextField(db_column='message', null=True)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('scen_no', models.ForeignKey(db_column='scen_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_scen_scen_conn', to='NWAD.scen')),
            ],
            options={
                'db_table': 'scen_conn',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='scen',
            name='scen_type',
            field=models.ForeignKey(db_column='scen_type', on_delete=django.db.models.deletion.CASCADE, related_name='fk_scen_type_scen', to='NWAD.scen_type'),
        ),
        migrations.AddField(
            model_name='bot',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_bot', to='NWAD.member'),
        ),
        migrations.AddField(
            model_name='api',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_api', to='NWAD.member'),
        ),
    ]
