# Generated by Django 4.1.3 on 2022-11-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0002_alter_api_member_no_token_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='rmk',
        ),
    ]
