# Generated by Django 4.1.3 on 2023-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(db_column='status', default='1', max_length=1),
        ),
    ]
