# Generated by Django 4.1.3 on 2022-11-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0003_remove_token_rmk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='token',
        ),
    ]
