# Generated by Django 4.1.3 on 2022-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0003_alter_api_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='private_key',
            field=models.TextField(db_column='private_key'),
        ),
    ]
