# Generated by Django 4.1.3 on 2022-11-30 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0004_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('token_no', models.AutoField(db_column='token_no', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=10)),
                ('token', models.TextField(db_column='token')),
                ('scope', models.TextField(db_column='scope')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_token', to='NWAD.api')),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_token', to='NWAD.member')),
            ],
            options={
                'db_table': 'token',
                'managed': True,
            },
        ),
    ]
