# Generated by Django 4.1.3 on 2022-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0005_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(db_column='type', max_length=20),
        ),
    ]
