# Generated by Django 4.1.3 on 2022-12-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0006_alter_token_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='member_no',
        ),
        migrations.RemoveField(
            model_name='token',
            name='api_no',
        ),
        migrations.RemoveField(
            model_name='token',
            name='member_no',
        ),
        migrations.DeleteModel(
            name='api',
        ),
        migrations.DeleteModel(
            name='bot',
        ),
        migrations.DeleteModel(
            name='token',
        ),
    ]
