# Generated by Django 4.1.3 on 2022-12-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0007_remove_bot_member_no_remove_token_api_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('api_no', models.AutoField(db_column='api_no', primary_key=True, serialize=False)),
                ('api_name', models.CharField(db_column='api_name', max_length=20)),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
                ('client_secret', models.CharField(db_column='client_secret', max_length=10)),
                ('service_account', models.CharField(db_column='service_account', max_length=50)),
                ('private_key', models.TextField(db_column='private_key')),
                ('scope', models.TextField(db_column='scope')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_api', to='NWAD.member')),
            ],
            options={
                'db_table': 'api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('token_no', models.AutoField(db_column='token_no', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=20)),
                ('token', models.TextField(db_column='token')),
                ('scope', models.TextField(db_column='scope')),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_token', to='NWAD.api')),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_token', to='NWAD.member')),
            ],
            options={
                'db_table': 'token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='bot',
            fields=[
                ('bot_no', models.AutoField(db_column='bot_no', primary_key=True, serialize=False)),
                ('bot_id', models.CharField(db_column='bot_id', max_length=10)),
                ('bot_secret', models.CharField(db_column='bot_secret', max_length=30)),
                ('bot_name', models.CharField(db_column='bot_name', max_length=10)),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_no_bot', to='NWAD.member')),
            ],
            options={
                'db_table': 'bot',
                'managed': True,
            },
        ),
    ]
