# Generated by Django 4.1.3 on 2022-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0008_api_token_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, db_column='reg_date'),
        ),
    ]
