# Generated by Django 4.1.3 on 2022-12-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0009_bot_reg_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='token',
        ),
    ]
