# Generated by Django 4.1.3 on 2022-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0011_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reg_date',
            field=models.DateTimeField(db_column='reg_date'),
        ),
    ]
