# Generated by Django 4.1.3 on 2022-12-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0016_scen_scen_type_scen_conn_scen_scen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scen',
            name='domain',
            field=models.CharField(db_column='domain', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scen',
            name='status',
            field=models.CharField(db_column='status', default='1', max_length=1),
        ),
    ]
