# Generated by Django 4.1.3 on 2022-12-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0017_alter_scen_domain_alter_scen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scen_conn',
            name='scen_no',
        ),
        migrations.AlterField(
            model_name='api',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_api', to='NWAD.member'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_bot', to='NWAD.member'),
        ),
        migrations.AlterField(
            model_name='token',
            name='member_no',
            field=models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_token', to='NWAD.member'),
        ),
        migrations.DeleteModel(
            name='scen',
        ),
        migrations.DeleteModel(
            name='scen_conn',
        ),
        migrations.DeleteModel(
            name='scen_type',
        ),
    ]
