# Generated by Django 4.1.3 on 2022-12-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0018_remove_scen_conn_scen_no_alter_api_member_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scen',
            fields=[
                ('scen_no', models.AutoField(db_column='scen_no', primary_key=True, serialize=False)),
                ('domain', models.CharField(db_column='domain', max_length=10, null=True)),
                ('channel', models.CharField(db_column='channel', max_length=40)),
                ('members', models.TextField(db_column='members')),
                ('status', models.CharField(db_column='status', default='1', max_length=1)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('api_no', models.ForeignKey(db_column='api_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_api_scen', to='NWAD.api')),
                ('bot_no', models.ForeignKey(db_column='bot_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_bot_scen', to='NWAD.bot')),
                ('member_no', models.ForeignKey(db_column='member_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_member_scen', to='NWAD.member')),
            ],
            options={
                'db_table': 'scen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scen_type',
            fields=[
                ('scen_type', models.AutoField(db_column='scen_type', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=20)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
            ],
            options={
                'db_table': 'scen_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scen_conn',
            fields=[
                ('conn_no', models.AutoField(db_column='conn_no', primary_key=True, serialize=False)),
                ('reporter', models.CharField(db_column='reporter', max_length=40, null=True)),
                ('approver', models.CharField(db_column='approver', max_length=40, null=True)),
                ('status', models.CharField(db_column='status', default='2', max_length=1)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='reg_date')),
                ('rmk', models.TextField(db_column='rmk', null=True)),
                ('scen_no', models.ForeignKey(db_column='scen_no', on_delete=django.db.models.deletion.CASCADE, related_name='fk_scen_scen_conn', to='NWAD.scen')),
            ],
            options={
                'db_table': 'scen_conn',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='scen',
            name='scen_type',
            field=models.ForeignKey(db_column='scen_type', on_delete=django.db.models.deletion.CASCADE, related_name='fk_scen_type_scen', to='NWAD.scen_type'),
        ),
    ]
