# Generated by Django 4.1.3 on 2022-12-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0019_scen_scen_type_scen_conn_scen_scen_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scen_conn',
            name='scen_no',
        ),
        migrations.DeleteModel(
            name='scen',
        ),
        migrations.DeleteModel(
            name='scen_conn',
        ),
    ]
