# Generated by Django 4.1.3 on 2022-12-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0021_scen_scen_conn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='member_no',
        ),
    ]
