# Generated by Django 4.1.3 on 2022-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0022_remove_token_member_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='scen_conn',
            name='message',
            field=models.TextField(db_column='message', null=True),
        ),
    ]
