# Generated by Django 4.1.3 on 2023-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0023_scen_conn_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='corp_name',
            field=models.TextField(db_column='corp_name', default='', max_length=50),
            preserve_default=False,
        ),
    ]
