# Generated by Django 4.1.3 on 2023-02-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0024_member_corp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scen',
            name='scen_name',
            field=models.CharField(db_column='scen_name', default='', max_length=20),
            preserve_default=False,
        ),
    ]
