# Generated by Django 4.1.3 on 2023-03-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0025_scen_scen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='client_secret',
            field=models.CharField(db_column='client_secret', max_length=24),
        ),
        migrations.AlterField(
            model_name='api',
            name='service_account',
            field=models.TextField(db_column='service_account'),
        ),
    ]
