# Generated by Django 4.1.3 on 2023-03-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0026_alter_api_client_secret_alter_api_service_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_secret',
            field=models.TextField(db_column='bot_secret'),
        ),
    ]
