# Generated by Django 4.1.3 on 2023-03-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NWAD', '0027_alter_bot_bot_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(db_column='bot_name', max_length=50),
        ),
    ]
